<?xml version="1.0"?>
<package format="2">
  <name>mpc_model_id_mismatch</name>
  <version>0.0.0</version>
  <description>The mpc_model_id_mismatch package</description>

  <maintainer email="d.benders@tudelft.nl">Dennis Benders</maintainer>

  <license>Apache License 2.0</license>

  <author>Dennis Benders</author>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>roscpp</depend>
  <exec_depend>px4_tools</exec_depend>

  <export>
  </export>
</package>