recorded_data:
  bag_dir: /media/storage/Downloads/agisim/bags
  bag_names:
    [
      2025-06-26_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_no_dist_no_meas_noise,
      2025-06-26_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_dist_meas_noise,
      2025-06-26_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_ccw_dist_meas_noise,
      2025-06-26_sim_falcon_mpc_model_mismatch_lemniscate_r1_f0dot1_cw_dist_meas_noise,
      2025-06-26_sim_falcon_mpc_model_mismatch_lemniscate_r1_f0dot1_ccw_dist_meas_noise,
    ]
  topic_names: [/step_control, /falcon/ground_truth/odometry, /w, /eta]
  # bag_names:
  #   [2025-06-26_gaz_falcon_mpc_model_id_inertia_matrix_dist_no_meas_noise]
  # topic_names: [/step_control, /falcon/ground_truth/odometry]

supported_topic_names: [/step_control, /falcon/ground_truth/odometry, /w, /eta]
